In [2]:
# Ejemplo clase

x = { "hola" : [3,4], "adios": ["Pepito", "Jose"]}
df = pd.DataFrame(data=x)
print(df)
print(type(df))

   hola   adios
0     3  Pepito
1     4    Jose
<class 'pandas.core.frame.DataFrame'>


In [8]:
df["adios"]

0    Pepito
1      Jose
Name: adios, dtype: object

In [6]:
df["hola"].values

array([3, 4], dtype=int64)

## Ejercicio 1
Importa la libreria de `pandas` y `numpy`. ¿Qué versión de la librería `pandas` tienes?

In [1]:
import pandas as pd 
import numpy as np

In [3]:
pd.__version__

'1.2.4'

## Ejercicio 2
Lee el archivo CSV de la liga. Guarda el DataFrame en una variable llamada `df`. [Usa el método `read_csv` de `pandas`](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.read_csv.html).

In [12]:
# Diferencia entre pd.DataFrame y read_csv: Tenemos que leer primero el read_csv para leerlo, esto devuelve como data frame

df = pd.read_csv("laliga.csv")
df

Unnamed: 0   season  division  round           localTeam    visitorTeam  \
0          26201  2005-06         1      1  Atletico de Bilbao  Real Sociedad   
1          26202  2005-06         1      1              Alaves      Barcelona   
2          26203  2005-06         1      1            Valencia          Betis   
3          26204  2005-06         1      1  Atletico de Madrid       Zaragoza   
4          26205  2005-06         1      1               Cadiz    Real Madrid   
...          ...      ...       ...    ...                 ...            ...   
4935       36680  2017-18         1     38          Villarreal    Real Madrid   
4936       36681  2017-18         1     38  Atletico de Bilbao        Espanol   
4937       36682  2017-18         1     38           Barcelona  Real Sociedad   
4938       36683  2017-18         1     38            Valencia      Deportivo   
4939       36684  2017-18         1     38  Atletico de Madrid          Eibar   

      localGoals  visitorGoals        date   timestamp  
0              3             0  27/08/2005  1125093600  
1              0             0  27/08/2005  1125093600  
2              1             0  27/08/2005  1125093600  
3              0             0  28/08/2005  1125180000  
4              1             2  28/08/2005  1125180000  
...          ...           ...         ...         ...  
4935           2             2  19/05/2018  1526680800  
4936           0             1  20/05/2018  1526767200  
4937           1             0  20/05/2018  1526767200  
4938           2             1  20/05/2018  1526767200  
4939           2             2  20/05/2018  1526767200  

[4940 rows x 10 columns]

## Ejercicio 3
Obtén por pantalla los 4 primero registros

In [13]:
df[:4]

Unnamed: 0   season  division  round           localTeam    visitorTeam  \
0       26201  2005-06         1      1  Atletico de Bilbao  Real Sociedad   
1       26202  2005-06         1      1              Alaves      Barcelona   
2       26203  2005-06         1      1            Valencia          Betis   
3       26204  2005-06         1      1  Atletico de Madrid       Zaragoza   

   localGoals  visitorGoals        date   timestamp  
0           3             0  27/08/2005  1125093600  
1           0             0  27/08/2005  1125093600  
2           1             0  27/08/2005  1125093600  
3           0             0  28/08/2005  1125180000

## Ejercicio 4
Obtén en un array de `numpy` todos los valores del DataFrame

In [14]:
array = np.array([pd.DataFrame(df)])
array

array([[[26201, '2005-06', 1, ..., 0, '27/08/2005', 1125093600],
        [26202, '2005-06', 1, ..., 0, '27/08/2005', 1125093600],
        [26203, '2005-06', 1, ..., 0, '27/08/2005', 1125093600],
        ...,
        [36682, '2017-18', 1, ..., 0, '20/05/2018', 1526767200],
        [36683, '2017-18', 1, ..., 1, '20/05/2018', 1526767200],
        [36684, '2017-18', 1, ..., 2, '20/05/2018', 1526767200]]],
      dtype=object)

In [16]:
df.values

array([[26201, '2005-06', 1, ..., 0, '27/08/2005', 1125093600],
       [26202, '2005-06', 1, ..., 0, '27/08/2005', 1125093600],
       [26203, '2005-06', 1, ..., 0, '27/08/2005', 1125093600],
       ...,
       [36682, '2017-18', 1, ..., 0, '20/05/2018', 1526767200],
       [36683, '2017-18', 1, ..., 1, '20/05/2018', 1526767200],
       [36684, '2017-18', 1, ..., 2, '20/05/2018', 1526767200]],
      dtype=object)

## Ejercicio 5
¿Cuáles son las columnas de `df`?

In [18]:
df.dtypes

Unnamed: 0       int64
season          object
division         int64
round            int64
localTeam       object
visitorTeam     object
localGoals       int64
visitorGoals     int64
date            object
timestamp        int64
dtype: object

## Ejercicio 6
Crea un `Series` con la [población de Madrid, Galicia, Murcia y Andalucía](https://es.wikipedia.org/wiki/Anexo:Comunidades_y_ciudades_aut%C3%B3nomas_de_Espa%C3%B1a). Llamalo `poblacion`.

- Madrid: 6685471
- Galicia: 2698764
- Murcia: 1494442
- Andalucía: 8446561


In [21]:
poblacion = pd.Series([6685471, 2698764, 1494442, 8446561],
                 index=['Madrid', 'Galicia', 'Murcia', 'Andalucia'])
print(poblacion)

Madrid       6685471
Galicia      2698764
Murcia       1494442
Andalucia    8446561
dtype: int64


## Ejercicio 7
Obtén un array de `numpy` con los valores del `Series`.

Saca también sus índices, y los valores de sus índices.

In [22]:
poblacion.values 

array([6685471, 2698764, 1494442, 8446561], dtype=int64)

In [23]:
poblacion.index

Index(['Madrid', 'Galicia', 'Murcia', 'Andalucia'], dtype='object')

## Ejercicio 8
1. ¿Qué población hay en el primer elemento del `Series`?
2. ¿Qué población hay en Galicia?
3. Imprime por pantalla las poblaciones de Galicia, Andalucía y las comunidades autónomas que se encuentren entre ambas, dentro del `Series`.
4. Comprueba con un output booleano que `Galicia` se encuentra entre los índices del `Index`.
5. Realiza los apartados 1,2,3 pero esta vez de una manera diferente.

In [25]:
#1
poblacion[0]

6685471

In [26]:
#2
poblacion["Galicia"]

2698764

In [30]:
#3
print(poblacion.values[1:])

[2698764 1494442 8446561]


In [31]:
"Galicia" in poblacion.index

True

In [41]:
print("Poblacion madrid:", poblacion["Madrid"])
print("Poblacion galicia:", poblacion[1])
print(poblacion['Galicia':'Andalucia'].values)

Poblacion madrid: 6685471
Poblacion galicia: 2698764
[2698764 1494442 8446561]


## Ejercicio 9
A partir de las comunidades autónomas anteriores, crea un `Series` con [la tasa de paro](https://es.statista.com/estadisticas/941646/prevision-de-la-tasa-de-paro-por-comunidad-autonoma-espana/) en dichas comunidades autónomas.

Con la tasa de paro y las poblaciones, crea un DataFrame de pandas. Llámalo `data`.

- Madrid: 9.99
- Galicia: 11.74
- Murcia: 16.08
- Andalucía: 20.8

In [44]:
paro = pd.Series([9.99, 11.74, 16.08, 20.8],
                 index=['Madrid', 'Galicia', 'Murcia', 'Andalucia'])
print(paro)

Madrid        9.99
Galicia      11.74
Murcia       16.08
Andalucia    20.80
dtype: float64


In [54]:
data = pd.DataFrame({'Poblacion': poblacion, 'Paro': paro})
data

Poblacion   Paro
Madrid       6685471   9.99
Galicia      2698764  11.74
Murcia       1494442  16.08
Andalucia    8446561  20.80

## Ejercicio 10
Imprime por pantalla la población, y la tasa de paro. Por separado

In [47]:
data['Poblacion']

Madrid       6685471
Galicia      2698764
Murcia       1494442
Andalucia    8446561
Name: Poblacion, dtype: int64

In [48]:
data['Paro']

Madrid        9.99
Galicia      11.74
Murcia       16.08
Andalucia    20.80
Name: Paro, dtype: float64

## Ejercicio 11
Crea un nuevo Data Frame (`data2`), que sea igual que `data`, pero con una nueva columna, que lleve [la superficie de las Comunidades Autónomas](https://es.wikipedia.org/wiki/Anexo:Comunidades_y_ciudades_aut%C3%B3nomas_de_Espa%C3%B1a).

- Madrid: 8028
- Galicia: 29575
- Murcia: 11314
- Andalucía: 87599

In [53]:
#Añadiendo la columna al mismo DataFrame
superficie = [8028, 29575, 11314, 87599]
data["Superficie"] = superficie

In [50]:
data

Poblacion   Paro  Superficie
Madrid       6685471   9.99        8028
Galicia      2698764  11.74       29575
Murcia       1494442  16.08       11314
Andalucia    8446561  20.80       87599

In [55]:
#Haciendo un nuevo DataFrame
superficie = pd.Series([8028, 29575, 11314, 87599],
                 index=['Madrid', 'Galicia', 'Murcia', 'Andalucia'])

In [73]:
data2 = pd.DataFrame({'Poblacion': poblacion, 'Paro': paro, 'Superficie': superficie})
data2

Poblacion   Paro    Superficie
Madrid       6685471   9.99    832.769183
Galicia      2698764  11.74     91.251530
Murcia       1494442  16.08  11314.000000
Andalucia    8446561  20.80     96.423030

## Ejercicio 12
Calcula la densidad de población (hab/km^2) en una nueva columna del dataframe `data2` que se llame `Densidad`.

In [75]:
# Resultado: 
data2["Densidad"] = data2["Poblacion"]/data2["Superficie"]
data2

Poblacion   Paro    Superficie      Densidad
Madrid       6685471   9.99    832.769183   8028.000000
Galicia      2698764  11.74     91.251530  29575.000000
Murcia       1494442  16.08  11314.000000    132.087856
Andalucia    8446561  20.80     96.423030  87599.000000

In [76]:
# Creando una nueva serie
densidad= pd.Series([poblacion[0]/superficie[0], poblacion[1]/superficie[1], poblacion[2]/superficie[2], poblacion[-1]/superficie[-1]],
                 index=['Madrid', 'Galicia', 'Murcia', 'Andalucia'])
densidad

Madrid        8028.000000
Galicia      29575.000000
Murcia         132.087856
Andalucia    87599.000000
dtype: float64

In [77]:
data2['Densidad'] = densidad
data2

Poblacion   Paro    Superficie      Densidad
Madrid       6685471   9.99    832.769183   8028.000000
Galicia      2698764  11.74     91.251530  29575.000000
Murcia       1494442  16.08  11314.000000    132.087856
Andalucia    8446561  20.80     96.423030  87599.000000