### 1. 

En el archivo "logistic_regression_digits" hemos visto un ejemplo multiclase. Elimina todas las imágenes y etiqueta (label) cuyo valor del label no sea 1 o 9. Es decir, elimina todos los dígitos y quédate solo con los dígitos 1 y 9.

Ahora, realiza un entrenamiento con logistic regression con los nuevos datos:

- ¿Se mejora la precisión del algoritmo con dos clases? ¿por qué?

LogisticRegression() es una clase que tiene varios parámetros de entrada. Investiga (modifica, prueba) los argumentos y comenta si modificando algunas de ellas se mejora el porcentaje de acierto del problema (probar al menos 2 diferentes)

https://scikit-learn.org/stable/modules/generated/sklearn.linear_model.LogisticRegression.html

In [1]:
import numpy as np

In [2]:
from sklearn.datasets import load_digits
digits = load_digits()
digits.keys()

dict_keys(['data', 'target', 'frame', 'feature_names', 'target_names', 'images', 'DESCR'])

In [3]:
import pandas as pd

df = pd.DataFrame(data= np.c_[digits['data'], digits['target']])
df

0    1     2     3     4     5    6    7    8    9   ...   55   56  \
0     0.0  0.0   5.0  13.0   9.0   1.0  0.0  0.0  0.0  0.0  ...  0.0  0.0   
1     0.0  0.0   0.0  12.0  13.0   5.0  0.0  0.0  0.0  0.0  ...  0.0  0.0   
2     0.0  0.0   0.0   4.0  15.0  12.0  0.0  0.0  0.0  0.0  ...  0.0  0.0   
3     0.0  0.0   7.0  15.0  13.0   1.0  0.0  0.0  0.0  8.0  ...  0.0  0.0   
4     0.0  0.0   0.0   1.0  11.0   0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0   
...   ...  ...   ...   ...   ...   ...  ...  ...  ...  ...  ...  ...  ...   
1792  0.0  0.0   4.0  10.0  13.0   6.0  0.0  0.0  0.0  1.0  ...  0.0  0.0   
1793  0.0  0.0   6.0  16.0  13.0  11.0  1.0  0.0  0.0  0.0  ...  0.0  0.0   
1794  0.0  0.0   1.0  11.0  15.0   1.0  0.0  0.0  0.0  0.0  ...  0.0  0.0   
1795  0.0  0.0   2.0  10.0   7.0   0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0   
1796  0.0  0.0  10.0  14.0   8.0   1.0  0.0  0.0  0.0  2.0  ...  0.0  0.0   

       57   58    59    60    61   62   63   64  
0     0.0  6.0  13.0  10.0   0.0  0.0  0.0  0.0  
1     0.0  0.0  11.0  16.0  10.0  0.0  0.0  1.0  
2     0.0  0.0   3.0  11.0  16.0  9.0  0.0  2.0  
3     0.0  7.0  13.0  13.0   9.0  0.0  0.0  3.0  
4     0.0  0.0   2.0  16.0   4.0  0.0  0.0  4.0  
...   ...  ...   ...   ...   ...  ...  ...  ...  
1792  0.0  2.0  14.0  15.0   9.0  0.0  0.0  9.0  
1793  0.0  6.0  16.0  14.0   6.0  0.0  0.0  0.0  
1794  0.0  2.0   9.0  13.0   6.0  0.0  0.0  8.0  
1795  0.0  5.0  12.0  16.0  12.0  0.0  0.0  9.0  
1796  1.0  8.0  12.0  14.0  12.0  1.0  0.0  8.0  

[1797 rows x 65 columns]

In [4]:
df[64]

0       0.0
1       1.0
2       2.0
3       3.0
4       4.0
       ... 
1792    9.0
1793    0.0
1794    8.0
1795    9.0
1796    8.0
Name: 64, Length: 1797, dtype: float64

In [5]:
df1 = df.drop(df[df[64] != 1.0].index)

In [6]:
df1

0    1    2     3     4     5    6    7    8    9   ...   55   56   57  \
1     0.0  0.0  0.0  12.0  13.0   5.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
11    0.0  0.0  0.0   0.0  14.0  13.0  1.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
21    0.0  0.0  0.0   2.0  16.0  16.0  2.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
42    0.0  0.0  0.0   0.0  12.0   5.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
47    0.0  0.0  0.0   1.0  11.0   9.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
...   ...  ...  ...   ...   ...   ...  ...  ...  ...  ...  ...  ...  ...  ...   
1752  0.0  0.0  4.0  10.0  12.0   7.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
1757  0.0  0.0  4.0  16.0  16.0   8.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
1760  0.0  0.0  1.0  12.0  10.0   3.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
1766  0.0  0.0  8.0  12.0  11.0   6.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
1774  0.0  0.0  6.0  12.0  12.0   6.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   

       58    59    60    61   62   63   64  
1     0.0  11.0  16.0  10.0  0.0  0.0  1.0  
11    0.0   1.0  13.0  16.0  1.0  0.0  1.0  
21    0.0   2.0  12.0  15.0  4.0  0.0  1.0  
42    0.0   3.0  16.0   8.0  0.0  0.0  1.0  
47    0.0   2.0  14.0   6.0  0.0  0.0  1.0  
...   ...   ...   ...   ...  ...  ...  ...  
1752  1.0   9.0  10.0   0.0  0.0  0.0  1.0  
1757  6.0  12.0  12.0   2.0  0.0  0.0  1.0  
1760  1.0   7.0  12.0  10.0  0.0  0.0  1.0  
1766  4.0  11.0  12.0   7.0  0.0  0.0  1.0  
1774  2.0  11.0  10.0   4.0  0.0  0.0  1.0  

[182 rows x 65 columns]

In [7]:
df9 = df.drop(df[df[64] != 9.0].index)

In [8]:
df9

0    1     2     3     4    5    6    7    8    9   ...   55   56   57  \
9     0.0  0.0  11.0  12.0   0.0  0.0  0.0  0.0  0.0  2.0  ...  0.0  0.0  0.0   
19    0.0  0.0   6.0  14.0   4.0  0.0  0.0  0.0  0.0  0.0  ...  2.0  0.0  0.0   
29    0.0  0.0   9.0  13.0   7.0  0.0  0.0  0.0  0.0  0.0  ...  2.0  0.0  0.0   
31    0.0  0.0   2.0  13.0   8.0  0.0  0.0  0.0  0.0  0.0  ...  2.0  0.0  0.0   
37    0.0  0.0  13.0  10.0   1.0  0.0  0.0  0.0  0.0  5.0  ...  0.0  0.0  0.0   
...   ...  ...   ...   ...   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
1759  0.0  0.0   7.0  16.0   9.0  8.0  2.0  0.0  0.0  5.0  ...  0.0  0.0  0.0   
1772  0.0  0.0   5.0  14.0  11.0  8.0  0.0  0.0  0.0  4.0  ...  0.0  0.0  0.0   
1786  0.0  0.0   4.0  14.0  15.0  6.0  0.0  0.0  0.0  5.0  ...  0.0  0.0  0.0   
1792  0.0  0.0   4.0  10.0  13.0  6.0  0.0  0.0  0.0  1.0  ...  0.0  0.0  0.0   
1795  0.0  0.0   2.0  10.0   7.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   

        58    59    60    61    62   63   64  
9      9.0  12.0  13.0   3.0   0.0  0.0  9.0  
19     7.0  16.0  16.0  13.0  11.0  1.0  9.0  
29     7.0  12.0  12.0  12.0  11.0  0.0  9.0  
31     2.0  15.0  13.0  14.0  13.0  2.0  9.0  
37    13.0  13.0  15.0  16.0  13.0  0.0  9.0  
...    ...   ...   ...   ...   ...  ...  ...  
1759   7.0  15.0  14.0   7.0   0.0  0.0  9.0  
1772   7.0  15.0  12.0   5.0   0.0  0.0  9.0  
1786   4.0  13.0  15.0   9.0   0.0  0.0  9.0  
1792   2.0  14.0  15.0   9.0   0.0  0.0  9.0  
1795   5.0  12.0  16.0  12.0   0.0  0.0  9.0  

[180 rows x 65 columns]

In [9]:
df = pd.concat([df1, df9], axis=0)

In [11]:
df.reset_index(inplace=True, drop=True)

In [12]:
df

0    1    2     3     4     5    6    7    8    9   ...   55   56   57  \
0    0.0  0.0  0.0  12.0  13.0   5.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
1    0.0  0.0  0.0   0.0  14.0  13.0  1.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
2    0.0  0.0  0.0   2.0  16.0  16.0  2.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
3    0.0  0.0  0.0   0.0  12.0   5.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
4    0.0  0.0  0.0   1.0  11.0   9.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
..   ...  ...  ...   ...   ...   ...  ...  ...  ...  ...  ...  ...  ...  ...   
357  0.0  0.0  7.0  16.0   9.0   8.0  2.0  0.0  0.0  5.0  ...  0.0  0.0  0.0   
358  0.0  0.0  5.0  14.0  11.0   8.0  0.0  0.0  0.0  4.0  ...  0.0  0.0  0.0   
359  0.0  0.0  4.0  14.0  15.0   6.0  0.0  0.0  0.0  5.0  ...  0.0  0.0  0.0   
360  0.0  0.0  4.0  10.0  13.0   6.0  0.0  0.0  0.0  1.0  ...  0.0  0.0  0.0   
361  0.0  0.0  2.0  10.0   7.0   0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   

      58    59    60    61   62   63   64  
0    0.0  11.0  16.0  10.0  0.0  0.0  1.0  
1    0.0   1.0  13.0  16.0  1.0  0.0  1.0  
2    0.0   2.0  12.0  15.0  4.0  0.0  1.0  
3    0.0   3.0  16.0   8.0  0.0  0.0  1.0  
4    0.0   2.0  14.0   6.0  0.0  0.0  1.0  
..   ...   ...   ...   ...  ...  ...  ...  
357  7.0  15.0  14.0   7.0  0.0  0.0  9.0  
358  7.0  15.0  12.0   5.0  0.0  0.0  9.0  
359  4.0  13.0  15.0   9.0  0.0  0.0  9.0  
360  2.0  14.0  15.0   9.0  0.0  0.0  9.0  
361  5.0  12.0  16.0  12.0  0.0  0.0  9.0  

[362 rows x 65 columns]

In [17]:
from sklearn import linear_model
model = linear_model.LogisticRegression(max_iter=9999)

In [18]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(digits.data, digits.target, test_size=0.15, random_state=3)

In [19]:
model.fit(x_train, y_train)

LogisticRegression(max_iter=9999)

In [20]:
model.score(x_train, y_train)

1.0

In [21]:
model.score(x_test, y_test)


0.9629629629629629

In [23]:
import sklearn.metrics as metrics
predictions = model.predict(x_test)
cm = metrics.confusion_matrix(y_test, predictions)
print(cm)

[[38  0  0  0  0  0  0  0  0  0]
 [ 0 23  0  0  0  0  0  0  0  0]
 [ 0  0 25  0  0  0  0  0  0  0]
 [ 0  0  0 30  0  0  0  0  0  0]
 [ 0  0  0  0 28  0  0  1  1  0]
 [ 0  0  0  0  1 25  0  0  0  4]
 [ 0  1  0  0  0  0 16  0  0  0]
 [ 0  0  0  0  0  0  0 34  0  0]
 [ 0  0  0  0  0  1  0  0 19  0]
 [ 0  0  0  0  0  0  0  0  1 22]]
