# Ejercicios Numpy II

## Ejercicio 1
1. Crea un array que vaya del 0 al 9 y que se llame `my_array`
2. Imprime por pantalla los elementos [9 7 5 3 1] en ese orden.

In [1]:
import numpy as np

In [64]:
my_array = np.array(range(10))
print(my_array)
print(my_array[::-2])

[0 1 2 3 4 5 6 7 8 9]
[9 7 5 3 1]


In [23]:
my_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## Ejercicio 2
Imprime por pantalla la secuencia [[8 7]] del array `my_array`

In [22]:
print(my_array[8:6:-1])

[8 7]


## Ejercicio 3
Imprime por pantalla la secuencia [[2 1 0]] de `my_array`

In [30]:
print(my_array[2::-1])

[2 1 0]


## Ejercicio 4
1. Crea una matriz de 4x5, con una secuencia del 1 al 20
2. Invierte totalmente la matriz. Tanto las filas, como las columnas

In [31]:
import random

In [61]:
matriz = np.arange(1,21).reshape(4,5)
matriz

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [68]:
matriz2 = np.array(range(1,21)).reshape(4,5)
matriz2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [69]:
import time

In [72]:
%%timeit 
np.array(range(1,21)).reshape(4,5)

3.64 µs ± 236 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [74]:
%%timeit 
np.arange(1,21).reshape(4,5)

799 ns ± 21.2 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [59]:
matriz[::-1,::-1] # Invertir filas y columnas

array([[20, 19, 18, 17, 16],
       [15, 14, 13, 12, 11],
       [10,  9,  8,  7,  6],
       [ 5,  4,  3,  2,  1]])

## Ejercicio 5

Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[1, 2],
       [6, 7]])
```

In [55]:
array = np.concatenate([[my_array[1:3]],[my_array[6:8]]])
array

array([[1, 2],
       [6, 7]])

## Ejercicio 6
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[ 1,  3,  5],
       [11, 13, 15]])
```

In [75]:
matriz

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [82]:
matriz[0][::2]

array([1, 3, 5])

In [83]:
matriz[-2][::2]

array([11, 13, 15])

In [85]:
np.concatenate([[matriz[0][::2]],[matriz[-2][::2]]])

array([[ 1,  3,  5],
       [11, 13, 15]])

## Ejercicio 7
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[ 5,  4,  3,  2,  1],
       [10,  9,  8,  7,  6],
       [15, 14, 13, 12, 11]])
```

In [87]:
matriz

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [101]:
matriz[:-1, ::-1]

array([[ 5,  4,  3,  2,  1],
       [10,  9,  8,  7,  6],
       [15, 14, 13, 12, 11]])

In [107]:
np.concatenate([matriz[:1, ::-1],matriz[-2:, ::-1]])

array([[ 5,  4,  3,  2,  1],
       [15, 14, 13, 12, 11],
       [20, 19, 18, 17, 16]])

In [96]:
array_1, array_2, array_3, array_4 = np.vsplit(matriz,4)
np.concatenate([array_1[::,::-1],array_3[::,::-1],array_4[::,::-1]]).reshape(3,5)

array([[ 5,  4,  3,  2,  1],
       [15, 14, 13, 12, 11],
       [20, 19, 18, 17, 16]])

In [95]:
array_1[::,::-1]

array([[5, 4, 3, 2, 1]])

## Ejercicio 8
Dado el siguiente array:

```Python
x = np.array(["Loro", "Perro", "Gato", "Loro", "Perro"])
```

Filtra el array para quedarte únicamente con los loros.

Resuélvelo de dos maneras diferentes

In [109]:
x = np.array(["Loro", "Perro", "Gato", "Loro", "Perro"])

In [113]:
x_bools = x == "Loro"
print(x_bools)
print(x[x_bools])

[ True False False  True False]
['Loro' 'Loro']


In [127]:
for animal in x:
    if animal == "Loro":
        a = np.array([animal])
print(np.concatenate([a,a]))

['Loro' 'Loro']


In [118]:
x = np.array(["Loro", "Perro", "Gato", "Loro", "Perro"])
x_num = np.array([0, 1, 1, 0, 1])

x[x_num == 0]

array(['Loro', 'Loro'], dtype='<U5')

## Ejercicio 9
Crea una secuencia de 20 elementos y transformala en un array compuesto por 2 matrices de 5x2

In [122]:
array = np.arange(20).reshape(2,5,-1)
array

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9]],

       [[10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]]])

In [123]:
array = np.arange(20).reshape(5,-1,2)
array

array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19]]])

## Ejercicio 10
Obtén el siguiente array, partiendo de la matriz del **ejercicio 4**
```Python
array([[20, 19, 18, 17, 16],
       [15, 14, 13, 12, 11],
       [10,  9,  8,  7,  6],
       [ 5,  4,  3,  2,  1]])
```

In [125]:
matriz

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [126]:
matriz[::-1,::-1]

array([[20, 19, 18, 17, 16],
       [15, 14, 13, 12, 11],
       [10,  9,  8,  7,  6],
       [ 5,  4,  3,  2,  1]])

## Ejercicio 11
Crea un array de 10 0s. ¿Cuánto ocupa en memoria?

Sustituye el 4to elemento por 1, e imprime el array por pantalla

In [132]:
ceros = np.zeros(10)
print(ceros)
ceros.nbytes

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


80

In [133]:
ceros[3] = 1
print(ceros)

[0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]


## Ejercicio 12
Crea un vector que vaya del 10 al 49

Inviértelo

In [135]:
vector = np.arange(10,50)
vector[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

## Ejericio 13
Encuentra los indices de los valores que no sean 0 del siguiente vector [[1,2,0,0,4,0]]. El output sería [[0, 1, 4]]. [Encuentra el método apropiado en la documentación.](https://numpy.org/doc/)

In [142]:
v = np.array([1,2,0,0,4,0])

In [143]:
np.where(v)

(array([0, 1, 4], dtype=int64),)

In [144]:
v = np.array([1,0,0,0,4,0])
np.where(v)

(array([0, 4], dtype=int64),)

In [148]:
v = np.array([1,0,1,0,4,0])
np.where(v == 1)

(array([0, 2], dtype=int64),)

## Ejercicio 14
Crea una matriz de numeros aleatorios 10x10. Encuentra los valores mínimo y máximo.

In [160]:
matriz_aleatoria = np.random.randint(1000,size=(10,10))
matriz_aleatoria

array([[362,  62, 453, 700, 407, 663, 339,  12, 283, 385],
       [710, 616, 586,  82, 609, 606, 656, 349, 967, 340],
       [ 63, 482, 346, 913, 701, 873, 583,   8, 579, 620],
       [933, 176, 669, 409, 812, 578, 159, 370,  97, 589],
       [764, 789, 731, 106, 643, 567, 161, 297, 791, 768],
       [ 82, 424, 770, 826, 985, 790, 899, 770, 991, 773],
       [430, 137, 274, 459, 305, 296, 955, 345, 985, 221],
       [376,  13, 481, 878, 268, 674, 888, 744, 914, 778],
       [376, 503, 967, 231,  91, 291, 450, 444,  41, 137],
       [  8,  54, 672, 852, 410, 653,  19, 875, 216, 921]])

In [161]:
matriz_aleatoria.max()

991

In [162]:
matriz_aleatoria.min()

8

In [163]:
matriz_aleatoria.max(),matriz_aleatoria.min()

(991, 8)

In [165]:
np.max(matriz_aleatoria),np.min(matriz_aleatoria) 

(991, 8)

In [166]:
%%timeit
matriz_aleatoria.max(),matriz_aleatoria.min()

4.01 µs ± 204 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [167]:
%%timeit
np.max(matriz_aleatoria),np.min(matriz_aleatoria) 

5.93 µs ± 105 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


## Ejercicio 15
Crea un vector aleatorio de tamaño 30 y calcula su media

In [170]:
vector_aleatorio = np.random.randint(100,size=30)
vector_aleatorio

array([ 9, 95, 77, 48, 47,  0, 69, 95, 79, 75, 46, 21, 91, 87, 72, 16, 11,
       80,  4, 84, 43, 65, 87, 98, 94,  4, 37, 42, 59, 27])

In [173]:
np.mean(vector_aleatorio)

55.4

In [174]:
vector_aleatorio.mean()

55.4

In [175]:
%%timeit
np.mean(vector_aleatorio)


6.56 µs ± 161 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [176]:
%%timeit
vector_aleatorio.mean()


5.34 µs ± 85 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [172]:
sum(vector_aleatorio)/30

55.4

## Ejercicio 16
Crea un array cuadrado de 2D, con las dimensiones que quieras, pero que todo el borde esté compuesto por 1s, y el interior por 0s

In [182]:
y = np.ones((6,6))
y

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [184]:
y[1:-1,1:-1] = 0
print(y)

[[1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1.]]


In [247]:
z = np.zeros((6,6))
z

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [248]:
z[0] = 1
z

array([[1., 1., 1., 1., 1., 1.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [249]:
z = np.zeros((6,6))
z[0:,0:1]=1
z

array([[1., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0.]])

In [250]:
z = np.zeros((6,6))
z[-1]=1
z

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1.]])

In [256]:
z = np.zeros((6,6))

z[0:,5:] = 1
z


array([[0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 1.]])

In [257]:
z = np.zeros((6,6))

z[0:,-1:] = 1
z

array([[0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 1.]])

## Ejercicio 17
Crea una matriz de 8x8, y rellénala con 0s y 1s. Tienes que replicar:
```Python
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
```

In [276]:
matrix = np.ones((8,8))
matrix

array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]])

In [277]:
matrix[::2,::2] = 0
matrix[1::2,1::2] = 0
matrix

array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

## Ejercicio 18
Replica la matriz del apartado anterior, pero en este caso usando [la función `tile`](https://numpy.org/doc/stable/reference/generated/numpy.tile.html)

In [290]:
x = np.array([[0,1],[1,0]])
x_tile = np.tile(x,(4,4))
x_tile

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

## Ejercicio 19
Crea una matriz aleatoria de 5x5 y normaliza sus valores. Para normalizar tienes que restar sus valores por la media(`np.mean`) y dividir el resultado por la desviación estándar(`np.std`).

In [292]:
matr_5x5 = np.random.randint(100,size=(5,5))
matr_5x5

array([[89, 70, 28, 40, 20],
       [71, 87, 70, 95, 36],
       [57, 99, 83, 80, 47],
       [74, 50, 48,  1, 98],
       [37, 18, 32, 82, 76]])

In [294]:
normalizado = (matr_5x5 - matr_5x5.mean()) / matr_5x5.std()
normalizado

array([[ 1.08311402,  0.38504189, -1.15806492, -0.71717726, -1.45199003],
       [ 0.42178253,  1.00963275,  0.38504189,  1.30355785, -0.86413982],
       [-0.09258641,  1.45052041,  0.86267019,  0.75244828, -0.45999279],
       [ 0.53200445, -0.34977088, -0.42325216, -2.15006216,  1.41377977],
       [-0.82739918, -1.52547131, -1.01110237,  0.82592955,  0.60548572]])

## Ejercicio 20
1. Crea una secuencia de números que vayan del 0 al 10.
2. Crea un nuevo array, que parta del anterior, pero sustituya todos los elementos entre el 3 y el 8, por el valor -1
3. Crea un nuevo array que niegue todos los elementos entre el 3 y el 8

In [305]:
secuencia = np.arange(11)
secuencia

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [306]:
secuencia_copy = secuencia.copy()

In [307]:
secuencia_copy[3:9] = -1 
secuencia_copy

array([ 0,  1,  2, -1, -1, -1, -1, -1, -1,  9, 10])

In [311]:
secuencia_bools = secuencia_copy != -1
print(secuencia_bools)
print(secuencia_copy[secuencia_bools])

[ True  True  True False False False False False False  True  True]
[ 0  1  2  9 10]


## Ejercicio 21 
#### Bonus track. Mini hundir la flota para ir practicando.
##### Te ayudará a entender la lógica de la tarea Hundir la Flota.
1. Crea un tablero de 10x10 relleno del carácter espacio ( ).
2. Posiciona un par de barcos en [(0,1), (1,1)] y [(1,3), (1,4), (1,5), (1,6)]. Los barcos serán Os mayúsculas. Como ves, un barco de dos posiciones de eslora y otro de cuatro.
3. Recibe un disparo en uno de los barcos, sustituyendo la O por una X
4. Recibe un disparo en agua, sustituyendo uno de los espacios por un guión: -
5. Ignorando los disparos recibidos, ahora prueba a posicionar otro barco de 4 posiciones dentro del tablero, pero **de manera ALEATORIA.**

**TIP apartado 5**: El barco tendrá una posición inicial aleatoria dentro del tablero, y una orientación también aleatoria (N,S,E,O).

Por ejemplo, si tu posicion inicial fuese (5,0) y la orientación O, no podrias ponerlo porque se sale del tablero. Ahora bien, si fuese orientación este, si podrías, y ocuparía las posiciones [(5,0), (5,1), (5,2), (5,3)]. Por tanto tendrás que iterar con un bucle si es posible encajar el barco en el tablero, y el bucle terminará cuando lo consigas encajar. **Ojo con las posiciones donde ya hay barco!!!**

Usa `import random` para elegir las coordenadas aleatorias.